services:
  - type: web
    name: procom-cp-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
      - key: KEY
        generateValue: true  # Render will generate a secret key
      - key: VITE_CONTEST_START
        value: "2026-02-07T15:00:00+05:00"
      - key: VITE_CONTEST_DURATION
        value: "180"
